spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campuzl
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
  jwt:
    secret: asien9sd8fafaw3re8se00gga9s8d89fas9e8a8g9fg9as8e9f9s8e8g8h8a9segfs

